title: Explainable AI for the Arts - XAIxArts
description: >
  The first international workshop on eXplainable AI for the Arts at the ACM Creativity and Cognition Conference 2023.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman